spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce?createDatabaseIfNotExist=true&userSSL=false&userUnicode=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

## Specify DBMS
  jpa:
    database: MYSQL
    show-sql: false
## Hibernate DDL auto (create, create-drop, update)
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
server:
  port: 8081

flickr:
  apiKey: ab7112fd9b1450d16a1a7b5dc4eb9e8c
  apiSecret: eef475997a6490b4
  appKey: 72157720881938004-899fcb4b7205b89e
  appSecret: 8d88ab1f70f2d3d1